name: spaceship
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10        
  - pip                
  - pip:
      - dvc[gdrive]   
      - scikit-learn   
      - pandas
      - matplotlib
      - seaborn
      - numpy
