name: spaceship
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  - matplotlib
  - seaborn
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - tensorflow
  - keras
  - torch
  - torchvision
  - pytorch-lightning
  - pip:
      - dvc[gdrive]
